version: '2.4'
services:
  # httpd
  click-web:
    image: docker.io/nginx:1.23-alpine
    container_name: click-web
    restart: unless-stopped
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./wwwroot:/var/www
    # normally behind centeral traefik defined in production-manifests/services/traefik
    ports:
      - "127.0.0.1:80:80"
    # join click-internal network
    networks:
      click-internal: {}

  # php-fpm
  click-php:
    # production: track "prod" tag on ghcr.io
    # image: ghcr.io/wetfish/click:prod
    # for development, build the image
    build: .
    container_name: click-php
    restart: unless-stopped
    # db connection info
    env_file:
      - ./php.env
    volumes:
      - ./wwwroot:/var/www
    tmpfs: /tmp
    networks:
      click-internal: {}
  
  # database
  click-db:
    image: docker.io/mariadb:10.10
    container_name: click-db
    restart: unless-stopped
    env_file:
      - ./mariadb.env
    # built-in healthcheck script
    healthcheck:
      test: ["healthcheck.sh", "--su=mysql", "--connect", "--innodb_initialized"]
      interval: 60s
      timeout: 5s
      retries: 5
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./db/data:/var/lib/mysql
    networks:
      click-internal: {}

networks:
  # ephemeral, created for us by compose
  click-internal:
    driver: bridge
