version: '2.4'
services:
  # httpd
  click-web:
    image: ghcr.io/wetfish/click:prod-nginx
    container_name: click-web
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    # join click-internal and traefik-backend networks
    networks:
      click-internal: {}
      traefik-backend: {}

  # php-fpm
  click-php:
    # production: track "prod" tag on ghcr.io
    image: ghcr.io/wetfish/click:prod-php
    container_name: click-php
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    # db connection info
    env_file:
      - ./php.env
    volumes:
      - ./config/php-fpm.conf:/etc/php/5.6/fpm/php-fpm.conf:ro
      - ./config/php-fpm-pool.conf:/etc/php/5.6/fpm/pool.d/www.conf:ro
      - ./config/php.ini:/etc/php/5.6/fpm/php.ini:ro
    tmpfs: /tmp
    networks:
      click-internal: {}
  
  # database
  click-db:
    image: docker.io/mariadb:10.10
    container_name: click-db
    restart: unless-stopped
    command: --sql-mode=""
    env_file:
      - ./mariadb.env
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./db/data:/var/lib/mysql
    networks:
      click-internal: {}


  # watchtower - automatically pull new container images
  # note: this does not update the repo
  # if deployment files have changed you will need to git pull && docker compose up -d manually
  click-watchtower:
    image: ghcr.io/containrrr/watchtower:1.5.3
    container_name: click-watchtower
    environment:
      - "WATCHTOWER_CLEANUP=true"
      - "WATCHTOWER_POLL_INTERVAL=30"
      - "WATCHTOWER_LABEL_ENABLE=true"
      - "NO_COLOR=true"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  # ephemeral, created for us by compose
  click-internal:
    driver: bridge
  # persistent, externally created
  traefik-backend:
    external: true
